---
- name: "GCP"
  secret_regexes:
    - (-----BEGIN PUBLIC KEY-----(\n|\r|\r\n)([0-9a-zA-Z\+/=]{64}(\n|\r|\r\n))*([0-9a-zA-Z\+/=]{1,63}(\n|\r|\r\n))?-----END PUBLIC KEY-----)|(-----BEGIN PRIVATE KEY-----(\n|\r|\r\n)([0-9a-zA-Z\+/=]{64}(\n|\r|\r\n))*([0-9a-zA-Z\+/=]{1,63}(\n|\r|\r\n))?-----END PRIVATE KEY-----)
    - "-----BEGIN PRIVATE KEY-----[a-zA-Z0-9\\+-=]+-----END PRIVATE KEY-----"
  keys_with_secerets:
    - keys:
        - "auth_uri"
        - "token_uri"
        - "auth_provider_x509_cert_url"
      secrets:
        - "https://[a-zA-Z-0-9./]*"
    - keys:
        - "private_key"
      secrets:
        - (-----BEGIN PUBLIC KEY-----(\n|\r|\r\n)([0-9a-zA-Z\+/=]{64}(\n|\r|\r\n))*([0-9a-zA-Z\+/=]{1,63}(\n|\r|\r\n))?-----END PUBLIC KEY-----)|(-----BEGIN PRIVATE KEY-----(\n|\r|\r\n)([0-9a-zA-Z\+/=]{64}(\n|\r|\r\n))*([0-9a-zA-Z\+/=]{1,63}(\n|\r|\r\n))?-----END PRIVATE KEY-----)
        - "-----BEGIN PRIVATE KEY-----[a-zA-Z0-9\\+-=]+-----END PRIVATE KEY-----"
  keys_required:
    - "auth_provider_x509_cert_url"

- name: "AWS"
  secret_regexes:
  keys_with_secerets:
    - keys:
        - "User name"
      secrets:
        - "[a-zA-Z-0-9]+"
    - keys:
        - "Password"
      secrets:
        - "[AKIA|ABIA|ACCA][0-9A-Z]{19}"
  keys_required:
    - "User name"
    - "Password"

- name: "PrivateKey"
  secret_regexes:
    - (-----BEGIN PUBLIC KEY-----(\n|\r|\r\n)([0-9a-zA-Z\+/=]{64}(\n|\r|\r\n))*([0-9a-zA-Z\+/=]{1,63}(\n|\r|\r\n))?-----END PUBLIC KEY-----)|(-----BEGIN PRIVATE KEY-----(\n|\r|\r\n)([0-9a-zA-Z\+/=]{64}(\n|\r|\r\n))*([0-9a-zA-Z\+/=]{1,63}(\n|\r|\r\n))?-----END PRIVATE KEY-----)
    - (-----BEGIN PRIVATE KEY-----[a-zA-Z0-9\+-=]+-----END PRIVATE KEY-----)
