---
- name: "Authorization HTTP Header"
  keys_with_secerets:
    - keys:
        - "Proxy-Authorization"
      secrets:
        - ([\s?\\]+Basic[\s?\\]+[-A-Za-z0-9+/]*={0,3})
        - ([\s?\\]+Basic[\s?\\]+[0-9A-Fa-f]*)
    - keys:
        - "Authorization"
      secrets:
        - ([\s?\\]+Basic[\s?\\]+[-A-Za-z0-9+/]*={0,3})
        - ([\s?\\]+Basic[\s?\\]+[0-9A-Fa-f]*)
    - keys:
        - "Authorization"
      secrets:
        - ([\s?\\]+Bearer[\s?\\]+[\w-]*\.[\w-]*\.[\w-]*)
        - ([\s?\\]+Bearer[\s?\\]+[\w=/-]+)
        - ([\s?\\]+Bearer[\s?\\]+[-A-Za-z0-9+/]*={0,3})
    - keys:
        - "Authorization"
      secrets:
        - ([\s?\n]Digest[\s?\\]+[\w]*=[\w=,"@.\s?]*)
        - ([\s?\n]Digest[\s?\\]+[\w]*=[\w=',/@.\s?]*)
    - keys:
        - "Authorization"
      secrets:
        - ([\s?\\]+DPoP[\s\w~\.\-\n\r]*)
    - keys:
        - "Authorization"
      secrets:
        - ([\s?\\]+GNAP[\s?\\]+[\w-]*\.[\w-]*\.[\w-]*)
        - ([\s?\\]+GNAP[\s?\\]+[\w-]*\.[\w-]*)
        - ([\s?\\]+GNAP[\s?\\]+[-A-Za-z0-9+/]*={0,3})
        - ([\s?\\]+GNAP[\s?\\]+[-A-Z0-9+/]*)
    - keys:
        - "Authorization"
      secrets:
        - ([\s?\\]+HOBA[\s?\\]+result="[\s\S]*?)
        - ([\s?\\]+HOBA[\s?\\]+result='[\s\S]*?)
    - keys:
        - "Authorization"
      secrets:
        - ([\s?\\]+Mutual[\s?\\]+[\w]*=[\w=,"@.\s?]*)
        - ([\s?\\]+Mutual[\s?\\]+[\w]*=[\w=',/@.\s?]*)
    - keys:
        - "Authorization"
      secrets:
        - ([\s?\\]+Negotiate[\s?\\]+[0-9A-Fa-f]*)
    - keys:
        - "Authorization"
      secrets:
        - ([\s?\\]+OAuth[\s?\\]+realm="[\w=,-/@.\s?]*"[,\s?]*oauth[\w]*="[\w=,"-/@.\s?]*")
    - keys:
        - "Authorization"
      secrets:
        - ([\s?\\]+PrivateToken[\s?\\]+token="[\s\S]*?")
        - ([\s?\\]+PrivateToken[\s?\\]+token=\'[\s\S]*?\')
    - keys:
        - "Authorization"
      secrets:
        - ([\s?\\]+SCRAM-SHA-1[\s?\\]+realm="[\w=,-/@.\s?]*"[,\s?*\n]*data=[\w=,-/@.\s?]*[,\s?*\n]*)
    - keys:
        - "Authorization"
      secrets:
        - ([\s?\n]SCRAM-SHA-256[\s?\\]+realm="[\w=,-/@.\s?]*"[,\s?*\n]*data=[\w=,-/@.\s?]*[,\s?*\n]*)
    - keys:
        - "Authorization"
      secrets:
        - ([\s?\\]+vapid[\s?\\]+[t]=[\w/@.\s?\|-]+,[\s?\\]+[k]=[\w/@.\s?\|-]+)
    - keys:
        - "Authorization"
      secrets:
        - ([\s?\\]+AWS4-HMAC-SHA256[\s?\\]+Credential=[\w=/-]+)
    - keys:
        - "Authorization"
      secrets:
        - ([\s?\\]+token[\s?\\]+[\w=/-]+)
    - keys:
        - "Authorization"
      secrets:
        - ([\s?\\]+JWT[\s?\w.\\]+)
    - keys:
        - "Authorization"
      secrets:
        - ([\s?\\]+NTLM[\s?\\]+[-A-Za-z0-9=]+)
    - keys:
        - "Authorization"
      secrets:
        - ([\s?\\]+Firebase[\s?\w.\\]+)
    - keys:
        - "Cookie"
      secrets:
        - ([\s?\\]+session=[\w=/-]+)
    - keys:
        - "Circle-Token"
      secrets:
        - ([\s?\\]+[\w=/-]+)
    - keys:
        - "Cookie"
      secrets:
        - ([\s?\\]+session=[\w=/-]+)
    - keys:
        - "X-Private-Token"
      secrets:
        - ([\s?\\]+private_[\w_=]+)
    - keys:
        - "Private-Token"
      secrets:
        - ([\s?\\]+[\w=/-]+)
    - keys:
        - "SSL-Client-Cert"
      secrets:
        - ([\s?\\]+[\w=/-]+)
    - keys:
        - "X-API-Key"
      secrets:
        - ([\s?\\]+[\w=/-]+)
    - keys:
        - "X-App-Token"
      secrets:
        - ([\s?\\]+[\w=/-]+)
    - keys:
        - "X-Auth-Token"
      secrets:
        - ([\s?\\]+[\w=/-]+)
    - keys:
        - "X-CSRF-Token"
      secrets:
        - ([\s?\\]+[\w=/-]+)
    - keys:
        - "X-Shopify-Access-Token"
      secrets:
        - ([\s?\\]+shpat_[\w=/-]+)
    - keys:
        - "API-Key"
      secrets:
        - ([\s?\\]+[\w=/-]+)
    - keys:
        - "X-Access-Token"
      secrets:
        - ([\s?\\]+[\w=/-]+)
    - keys:
        - "JWT"
      secrets:
        - ([\s?]+[\s\w~\.\-\n\r]+)
    - keys:
        - "X-Client-Id"
      secrets:
        - ([\s?\\]+client_[\w]+)
    - keys:
        - "X-Client-Secret"
      secrets:
        - ([\s?\\]+secret_[\w]+)
    - keys:
        - "X-Forwarded-Access-Token"
      secrets:
        - ([\s?\w.\\]+)
    - keys:
        - "X-Signature"
      secrets:
        - ([\s?\\]+hash_[0-9A-Fa-f]+)
    - keys:
        - "X-Hub-Signature"
      secrets:
        - ([\s?\\]+sha1=[0-9A-Fa-f]+)
    - keys:
        - "X-Auth-User"
      secrets:
        - ([\s?\\]+[\w_=]+)
    - keys:
        - "X-Auth-Pass"
      secrets:
        - ([\s?\\]+[\w_=]+)
    - keys:
        - "X-Auth"
      secrets:
        - ([\s?\\]+[\w_=]+)
    - keys:
        - "X-Auth-Key"
      secrets:
        - ([\s?\\]+key_[\w_=]+)
    - keys:
        - "X-Session-Key"
      secrets:
        - ([\s?\\]+session_[\w_=]+)
    - keys:
        - "X-Secret-Token"
      secrets:
        - ([\s?\\]+secret_[\w_=]+)
    - keys:
        - "X-User-Token"
      secrets:
        - ([\s?\\]+user_[\w_=]+)
    - keys:
        - "X-Refresh-Token"
      secrets:
        - ([\s?\\]+refresh_[\w_=]+)
    - keys:
        - "X-Custom-Auth"
      secrets:
        - ([\s?\\]+custom_[\w_=]+)
    - keys:
        - "X-Device-Token"
      secrets:
        - ([\s?\\]+device_[\w_=]+)
    - keys:
        - "X-Application-Key"
      secrets:
        - ([\s?\\]+app_[\w_=]+)
    - keys:
        - "X-Authentication"
      secrets:
        - ([\s?\\]+auth_[\w_=]+)
    - keys:
        - "X-OAuth-Token"
      secrets:
        - ([\s?\\]+oauth_[\w_=]+)
    - keys:
        - "X-Login-Token"
      secrets:
        - ([\s?\\]+login_[\w_=]+)
    - keys:
        - "X-Identity"
      secrets:
        - ([\s?\\]+identity_[\w_=]+)
    - keys:
        - "X-Credential"
      secrets:
        - ([\s?\\]+cred_[\w_=]+)
    - keys:
        - "X-Secret"
      secrets:
        - ([\s?\\]+secret_[\w_=]+)
    - keys:
        - "X-Key"
      secrets:
        - ([\s?\\]+key_[\w_=]+)
    - keys:
        - "X-Access"
      secrets:
        - ([\s?\\]+access_[\w_=]+)
    - keys:
        - "X-Signature-Key"
      secrets:
        - ([\s?\\]+sigkey_[\w_=]+)
    - keys:
        - "X-Verification-Key"
      secrets:
        - ([\s?\\]+verkey_[\w_=]+)
