---
- name: "GCP"
  secret_regexes:
    - (-----BEGIN[\w\s?]+KEY-----[\w\n\s?/+=]+-----END[\w\s?]+KEY-----)
  keys_with_secerets:
    - keys:
        - "auth_uri"
        - "token_uri"
        - "auth_provider_x509_cert_url"
      secrets:
        - "https://[a-zA-Z-0-9./]*"
    - keys:
        - "private_key"
      secrets:
        - (-----BEGIN[\w\s?]+KEY-----[\w\n\s?/+=]+-----END[\w\s?]+KEY-----)
  keys_required:
    - "auth_provider_x509_cert_url"

- name: "AWS"
  secret_regexes:
  keys_with_secerets:
    - keys:
        - "User name"
      secrets:
        - "[a-zA-Z-0-9]+"
    - keys:
        - "Password"
      secrets:
        - "[AKIA|ABIA|ACCA][0-9A-Z]{19}"
  keys_required:
    - "User name"
    - "Password"

- name: "Private Key"
  secret_regexes:
    - (-----BEGIN[\w\s?]+KEY-----[\w\n\s?/+=]+-----END[\w\s?]+KEY-----)

- name: "Public Key"
  secret_regexes:
    - ((ecdsa-sha2-nistp[0-9]+|ssh-ed25519|ssh-rsa|ssh-dss)[\s][\w+=/]+)

- name: "Base64 string"
  secret_regexes:
    - (?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)
