---
- name: "gcp"
  keys_required:
    - "private_key"
    - "private_key_id"
  keys_optional:
    - "client_email"
    - "client_id"
    - "auth_uri"
    - "token_uri "
    - "auth_provider_x509_cert_url"
    - "client_x509_cert_url"
  min_opt_match: 2

- name: "aws_token"
  keys_required:
    - "aws_access_key_id"
    - "aws_secret_access_key"
    - "aws_session_token"
  keys_optional:
  min_opt_match:

- name: "aws_credentials"
  keys_required:
    - "User name"
    - "Password"
  keys_optional:
  min_opt_match:

- name: "twitter"
  keys_required:
  keys_optional:
    - Api Key
    - Api Key Secret
    - Bearer Token
    - Access Token
    - Access Token Secret
  min_opt_match: 1
