---
- name: "GCP"
  secret_regexes:
    - (-----BEGIN[\w\s?]+KEY-----[\w\n\s?/+=]+-----END[\w\s?]+KEY-----)
  keys_with_secerets:
    - keys:
        - "auth_uri"
        - "token_uri"
        - "auth_provider_x509_cert_url"
      secrets:
        - "https://[a-zA-Z-0-9./]*"
    - keys:
        - "private_key"
      secrets:
        - (-----BEGIN[\w\s?]+KEY-----[\w\n\s?/+=]+-----END[\w\s?]+KEY-----)
  keys_required:
    - "auth_provider_x509_cert_url"

- name: "AWS"
  secret_regexes:
  keys_with_secerets:
    - keys:
        - "User name"
      secrets:
        - "[a-zA-Z-0-9]+"
    - keys:
        - "Password"
      secrets:
        - "[AKIA|ABIA|ACCA][0-9A-Z]{19}"
  keys_required:
    - "User name"
    - "Password"

- name: "PRIVATE KEY PEM"
  secret_regexes:
    - (-----BEGIN[\w\s?]+KEY-----[\w\n\s?/+=]+-----END[\w\s?]+KEY-----)

- name: "PUBLIC KEY PEM"
  secret_regexes:
    - ((ecdsa-sha2-nistp[0-9]+|ssh-ed25519|ssh-rsa|ssh-dss)[\s][\w+=/]+)

- name: "PRIVATE KEY BASE64"
  secret_regexes:
    - ([0-9a-zA-Z\+\/=]{64}(\n|\r|\r\n))*([0-9a-zA-Z\+\/=]{1,63}(\n|\r|\r\n))

- name: "Authorization HTTP Header"
  secret_regexes:
    - Proxy-Authorization([\s?\\]+Basic[\s?\\]+[-A-Za-z0-9+/]*={0,3})
    - Proxy-Authorization([\s?\\]+Basic[\s?\\]+[0-9A-Fa-f]*)
    - Authorization([\s?\\]+Basic[\s?\\]+[-A-Za-z0-9+/]*={0,3})
    - Authorization([\s?\\]+Basic[\s?\\]+[0-9A-Fa-f]*)
    - Authorization([\s?\\]+Bearer[\s?\\]+[\w-]*\.[\w-]*\.[\w-]*)
    - Authorization([\s?\\]+Bearer[\s?\\]+[\w=/-]+)
    - Authorization([\s?\\]+Bearer[\s?\\]+[-A-Za-z0-9+/]*={0,3})
    - Authorization([\s?\n]Digest[\s?\\]+[\w]*=[\w=,"@.\s?]*)
    - Authorization([\s?\n]Digest[\s?\\]+[\w]*=[\w=',/@.\s?]*)
    - Authorization([\s?\\]+DPoP[\s\w~\.\-\n\r]*)
    - Authorization([\s?\\]+GNAP[\s?\\]+[\w-]*\.[\w-]*\.[\w-]*)
    - Authorization([\s?\\]+GNAP[\s?\\]+[\w-]*\.[\w-]*)
    - Authorization([\s?\\]+GNAP[\s?\\]+[-A-Za-z0-9+/]*={0,3})
    - Authorization([\s?\\]+GNAP[\s?\\]+[-A-Z0-9+/]*)
    - Authorization([\s?\\]+HOBA[\s?\\]+result="[\s\S]*?)
    - Authorization([\s?\\]+HOBA[\s?\\]+result='[\s\S]*?)
    - Authorization([\s?\\]+Mutual[\s?\\]+[\w]*=[\w=,"@.\s?]*)
    - Authorization([\s?\\]+Mutual[\s?\\]+[\w]*=[\w=',/@.\s?]*)
    - Authorization([\s?\\]+Negotiate[\s?\\]+[0-9A-Fa-f]*)
    - Authorization([\s?\\]+OAuth[\s?\\]+realm="[\w=,-/@.\s?]*"[,\s?]*oauth[\w]*="[\w=,"-/@.\s?]*")
    - Authorization([\s?\\]+PrivateToken[\s?\\]+token="[\s\S]*?")
    - Authorization([\s?\\]+PrivateToken[\s?\\]+token=\'[\s\S]*?\')
    - Authorization([\s?\\]+SCRAM-SHA-1[\s?\\]+realm="[\w=,-/@.\s?]*"[,\s?*\n]*data=[\w=,-/@.\s?]*[,\s?*\n]*)
    - Authorization([\s?\n]SCRAM-SHA-256[\s?\\]+realm="[\w=,-/@.\s?]*"[,\s?*\n]*data=[\w=,-/@.\s?]*[,\s?*\n]*)
    - Authorization([\s?\\]+vapid[\s?\\]+[t]=[\w/@.\s?\|-]+,[\s?\\]+[k]=[\w/@.\s?\|-]+)
    - Authorization([\s?\\]+AWS4-HMAC-SHA256[\s?\\]+Credential=[\w=/-]+)
    - Authorization([\s?\\]+token[\s?\\]+[\w=/-]+)
    - Authorization([\s?\\]+JWT[\s?\w.\\]+)
    - Authorization([\s?\\]+NTLM[\s?\\]+[-A-Za-z0-9=]+)
    - Authorization([\s?\\]+Firebase[\s?\w.\\]+)
    - Cookie([\s?\\]+session=[\w=/-]+)
    - Circle-Token([\s?\\]+[\w=/-]+)
    - Cookie([\s?\\]+session=[\w=/-]+)
    - X-Private-Token([\s?\\]+private_[\w_=]+)
    - Private-Token([\s?\\]+[\w=/-]+)
    - SSL-Client-Cert([\s?\\]+[\w=/-]+)
    - X-API-Key([\s?\\]+[\w=/-]+)
    - X-App-Token([\s?\\]+[\w=/-]+)
    - X-Auth-Token([\s?\\]+[\w=/-]+)
    - X-CSRF-Token([\s?\\]+[\w=/-]+)
    - X-Shopify-Access-Token([\s?\\]+shpat_[\w=/-]+)
    - API-Key([\s?\\]+[\w=/-]+)
    - X-Access-Token([\s?\\]+[\w=/-]+)
    - JWT([\s?]+[\s\w~\.\-\n\r]+)
    - X-Client-Id([\s?\\]+client_[\w]+)
    - X-Client-Secret([\s?\\]+secret_[\w]+)
    - X-Forwarded-Access-Token([\s?\w.\\]+)
    - X-Signature([\s?\\]+hash_[0-9A-Fa-f]+)
    - X-Hub-Signature([\s?\\]+sha1=[0-9A-Fa-f]+)
    - X-Auth-User([\s?\\]+[\w_=]+)
    - X-Auth-Pass([\s?\\]+[\w_=]+)
    - X-Auth([\s?\\]+[\w_=]+)
    - X-Auth-Key([\s?\\]+key_[\w_=]+)
    - X-Session-Key([\s?\\]+session_[\w_=]+)
    - X-Secret-Token([\s?\\]+secret_[\w_=]+)
    - X-User-Token([\s?\\]+user_[\w_=]+)
    - X-Refresh-Token([\s?\\]+refresh_[\w_=]+)
    - X-Custom-Auth([\s?\\]+custom_[\w_=]+)
    - X-Device-Token([\s?\\]+device_[\w_=]+)
    - X-Application-Key([\s?\\]+app_[\w_=]+)
    - X-Authentication([\s?\\]+auth_[\w_=]+)
    - X-OAuth-Token([\s?\\]+oauth_[\w_=]+)
    - X-Login-Token([\s?\\]+login_[\w_=]+)
    - X-Identity([\s?\\]+identity_[\w_=]+)
    - X-Credential([\s?\\]+cred_[\w_=]+)
    - X-Secret([\s?\\]+secret_[\w_=]+)
    - X-Key([\s?\\]+key_[\w_=]+)
    - X-Access([\s?\\]+access_[\w_=]+)
    - X-Signature-Key([\s?\\]+sigkey_[\w_=]+)
    - X-Verification-Key([\s?\\]+verkey_[\w_=]+)
