---
- name: "gcp"
  secret_regexes:
    - "-----BEGIN PRIVATE KEY-----[\a-zA-Z0-9]*-----END PRIVATE KEY-----"
  keys_with_secerets:
    - keys:
        - "auth_uri"
        - "token_uri"
        - "auth_provider_x509_cert_url"
      secrets:
        - "https://[a-zA-Z-0-9./]*"
    - keys:
        - "private_key"
      secrets:
        - "-----BEGIN PRIVATE KEY-----[\a-zA-Z0-9]*-----END PRIVATE KEY-----"

- name: "aws"
  secret_regexes:
  keys_with_secerets:
    - keys:
        - "User"
      secrets:
        - "[a-zA-Z-0-9]+"
    - keys:
        - "Password"
      secrets:
        - "[AKIA|ABIA|ACCA][0-9A-Z]{19}"

- name: "ssl-certificate"
  secret_regexes:
    - "-----BEGIN PRIVATE KEY-----[\a-zA-Z0-9]*-----END PRIVATE KEY-----"
